# Generated by Django 4.0.3 on 2022-03-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_options_and_more'),
        ('quizzes', '0002_answer_index_question_index'),
    ]

    operations = [
    ]
