services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      elasticsearch:
        condition: service_healthy
    network_mode: "host"

  frontend:
    build: ./frontend
    network_mode: "host"

  celery:
    build: ./backend
    command: celery -A kahoot worker -l INFO
    volumes:
      - ./backend:/backend/code
    depends_on:
      - backend
      - rabbitmq
    network_mode: "host"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
    network_mode: "host"
 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    environment:
      - discovery.type=single-node
      # - xpack.security.enabled=false
      # - xpack.security.http.ssl.enabled=false
      # - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
    network_mode: "host"
    healthcheck:
      test: curl -u elastic:elastic -s -f localhost:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 100