# Generated by Django 4.0.3 on 2022-03-08 01:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import re


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_remove_game_players_players_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAnswerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.RenameField(
            model_name='players',
            old_name='games',
            new_name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='question_answers',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_quiz',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='game',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=django_fsm.FSMField(default='active', max_length=50, protected=True),
        ),
        migrations.DeleteModel(
            name='Question_Answer',
        ),
        migrations.AddField(
            model_name='playeranswerlist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='games.players'),
        ),
    ]
