# Generated by Django 4.0.3 on 2022-03-08 06:41

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_player_email_alter_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=django_fsm.FSMField(default='created', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='playeranswerlist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.player'),
        ),
    ]
