# Generated by Django 4.0.3 on 2022-03-08 06:49

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_state_alter_playeranswerlist_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='answers',
            field=models.CharField(default=None, max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlayerAnswerList',
        ),
    ]
