# Generated by Django 4.0.3 on 2022-03-08 07:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_game_quiz_game_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=django_fsm.FSMField(default='active', max_length=50, protected=True),
        ),
    ]
