# Generated by Django 4.0.10 on 2024-05-23 19:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_timer_player_answer_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timer',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='answer_bonus',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
