# Generated by Django 4.0.3 on 2022-03-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_player_uuid_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.CharField(default=None, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
